service: PhilipsTestTask
frameworkVersion: '3'


provider:
  name: aws
  stage: dev
  runtime: python3.9
  region: eu-central-1
  memorySize: 128
  timeout: 5
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/Announcement*"


plugins:
   - serverless-python-requirements
   - serverless-api-gateway-throttling


custom:
  pythonRequirements:
    dockerImage: mlupin/docker-lambda:python3.9-build
    slim: true
    dockerizePip: true
    layer: true
  apiGatewayThrottling:
    maxRequestsPerSecond: 3
    maxConcurrentRequests: 1


resources:
  Resources:
    Announcement:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Announcement
        AttributeDefinitions:
          - AttributeName: title
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: title
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package:
  patterns:
    - "!./**"
    - "service_api/**"


functions:

  GetAnnouncements:
    layers:
      - Ref: PythonRequirementsLambdaLayer
    handler: service_api/api_v1.get_announcements
    events:
      - http:
          path: /announcements
          method: get

  CreateAnnouncements:
    layers:
      - Ref: PythonRequirementsLambdaLayer
    handler: service_api/api_v1.create_announcements
    events:
      - http:
          path: /announcements
          method: post
