service: PhilipsTestTask
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  runtime: python3.9
  region: eu-central-1

functions:
  healthcheck:
    handler: service_api/api_v1.healthcheck
    events:
      - http:
          path: /api/v1/healthcheck
          method: get
